### ISSUE TITLE
Error with @atproto-xrpc-sever - ConsumerTooSlow

### ISSUE THREAD

**Issue by andrewpking** [bluesky-social/feed-generator#121]
When running my custom feed I get the error from the pm2 logs:

0|chastity-feed  | repo subscription errored XRPCError: ConsumerTooSlow
0|chastity-feed  |     at ensureChunkIsMessage (/var/www/alphabutt2.fans/custom-feed-bluesky/node_modules/.store/@atproto-xrpc-server-npm-0.6.4-be671e82a5/package/src/stream/stream.ts:35:11)
0|chastity-feed  |     at Subscription.[Symbol.asyncIterator] (/var/www/alphabutt2.fans/custom-feed-bluesky/node_modules/.store/@atproto-xrpc-server-npm-0.6.4-be671e82a5/package/src/stream/subscription.ts:36:49)
0|chastity-feed  |     at processTicksAndRejections (node:internal/process/task_queues:95:5) {
0|chastity-feed  |   error: 'ConsumerTooSlow',
0|chastity-feed  |   headers: undefined,
0|chastity-feed  |   success: false,
0|chastity-feed  |   status: 500
0|chastity-feed  | }

I'm not sure what this means. I'm using the default firehose.

**Comment by andrewpking** [comment]
The other issue I'm getting is with sqlite.db:

0|chastity-feed  | repo subscription could not handle message SqliteError: attempt to write a readonly database
0|chastity-feed  |     at SqliteConnection.executeQuery (/var/www/alphabutt2.fans/custom-feed-bluesky/node_modules/.store/kysely-npm-0.27.4-45859daee9/package/dist/cjs/dialect/sqlite/sqlite-driver.js:61:55)
0|chastity-feed  |     at /var/www/alphabutt2.fans/custom-feed-bluesky/node_modules/.store/kysely-npm-0.27.4-45859daee9/package/dist/cjs/query-executor/query-executor-base.js:37:45
0|chastity-feed  |     at DefaultConnectionProvider.provideConnection (/var/www/alphabutt2.fans/custom-feed-bluesky/node_modules/.store/kysely-npm-0.27.4-45859daee9/package/dist/cjs/driver/default-connection-provider.js:12:26)
0|chastity-feed  |     at runNextTicks (node:internal/process/task_queues:60:5)
0|chastity-feed  |     at processImmediate (node:internal/timers:449:9)
0|chastity-feed  |     at async DefaultQueryExecutor.executeQuery (/var/www/alphabutt2.fans/custom-feed-bluesky/node_modules/.store/kysely-npm-0.27.4-45859daee9/package/dist/cjs/query-executor/query-executor-base.js:36:16)
0|chastity-feed  |     at async InsertQueryBuilder.execute (/var/www/alphabutt2.fans/custom-feed-bluesky/node_modules/.store/kysely-npm-0.27.4-45859daee9/package/dist/cjs/query-builder/insert-query-builder.js:782:24) {
0|chastity-feed  |   code: 'UNKNOWN_SQLITE_ERROR_1544'
0|chastity-feed  | }

I tried changing it to writeable by the user I'm using to run this program on my VPS.

**Comment by andrewpking** [comment]
I was able to resolve this issue by giving write permissions to the user I'm running this server through to the parent directory, unfortunately that seems to be the only way to resolve this issue due to the way sqlite's js library works.
