### ISSUE TITLE
Looking for help on fetch error

### ISSUE THREAD

**Issue by Jacob-Liebert** [bluesky-social/feed-generator#24]
Anyone getting a fetch error when attempting to publishFeed with no modification to source code?

/Users/jakeliebert/Documents/bluesky-PM-feed-main/node_modules/@atproto/xrpc/src/client.ts:156
    throw new XRPCError(ResponseType.Unknown, String(e))
          ^
XRPCError: TypeError: fetch failed
    at Function.defaultFetchHandler [as fetch] (/Users/jakeliebert/Documents/bluesky-PM-feed-main/node_modules/@atproto/xrpc/src/client.ts:156:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async _AtpAgent._fetch (/Users/jakeliebert/Documents/bluesky-PM-feed-main/node_modules/@atproto/api/src/agent.ts:201:15)
    at async ServiceClient.call (/Users/jakeliebert/Documents/bluesky-PM-feed-main/node_modules/@atproto/xrpc/src/client.ts:104:17)
    at async _AtpAgent.login (/Users/jakeliebert/Documents/bluesky-PM-feed-main/node_modules/@atproto/api/src/agent.ts:120:19) {
  status: 1,
  error: 'TypeError: fetch failed',
  success: false
}
error Command failed with exit code 1.

**Comment by benharri** [comment]
Try running with node v18
