### ISSUE TITLE
RangeError: Could not decode varint error

### ISSUE THREAD

**Issue by maximesimoncelli** [bluesky-social/feed-generator#73]
Hello,

I'm currently implementing my own feed, and it works pretty well but I have these errors at random intervals:

```bash
repo subscription could not handle message RangeError: Could not decode varint
  at Object.read3 [as decode] (/home/bsky/app/node_modules/@atproto/repo/dist/index.js:13095:17)
  at readVarint (/home/bsky/app/node_modules/@atproto/repo/dist/index.js:24770:36)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async readHeader (/home/bsky/app/node_modules/@atproto/repo/dist/index.js:24775:19)
  at async decodeReaderComplete (/home/bsky/app/node_modules/@atproto/repo/dist/index.js:25015:40)
```
If a reproduction repo is needed, there you go: https://github.com/maximesimoncelli/dungeon-synth-bsky-feed

Thank you very much for your help :)

**Comment by EddyLuten** [comment]
@maximesimoncelli not sure why exactly, but after I ran `npm i` and `npm audit fix` in my feed app's directory, it's working again.

**Comment by maximesimoncelli** [comment]
@EddyLuten Thanks for the heads up. I will try to see what npm audit reports, maybe it is only a bug in one of the dependencies.

**Comment by jeffgca** [comment]
I've sen this in my own feed service:

```
repo subscription could not handle message RangeError: Could not decode varint
    at Object.read3 [as decode] (/Users/jeff/code/projects/bsky/posta/node_modules/node_modules/.pnpm/varint@6.0.0/node_modules/varint/decode.js:17:13)
    at readVarint (/Users/jeff/code/projects/bsky/posta/node_modules/node_modules/.pnpm/@ipld+car@3.2.3/node_modules/@ipld/car/esm/lib/decoder.js:12:20)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async readHeader (/Users/jeff/code/projects/bsky/posta/node_modules/node_modules/.pnpm/@ipld+car@3.2.3/node_modules/@ipld/car/esm/lib/decoder.js:17:18)
    at async decodeReaderComplete (/Users/jeff/code/projects/bsky/posta/node_modules/node_modules/.pnpm/@ipld+car@3.2.3/node_modules/@ipld/car/esm/lib/reader-browser.js:51:28)
```

It doesn't seem to cause problems, I think it's just running into some data it doesn't like at the ipld level.

**Comment by maximesimoncelli** [comment]
> I've sen this in my own feed service:
> 
> ```
> repo subscription could not handle message RangeError: Could not decode varint
>     at Object.read3 [as decode] (/Users/jeff/code/projects/bsky/posta/node_modules/node_modules/.pnpm/varint@6.0.0/node_modules/varint/decode.js:17:13)
>     at readVarint (/Users/jeff/code/projects/bsky/posta/node_modules/node_modules/.pnpm/@ipld+car@3.2.3/node_modules/@ipld/car/esm/lib/decoder.js:12:20)
>     at processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async readHeader (/Users/jeff/code/projects/bsky/posta/node_modules/node_modules/.pnpm/@ipld+car@3.2.3/node_modules/@ipld/car/esm/lib/decoder.js:17:18)
>     at async decodeReaderComplete (/Users/jeff/code/projects/bsky/posta/node_modules/node_modules/.pnpm/@ipld+car@3.2.3/node_modules/@ipld/car/esm/lib/reader-browser.js:51:28)
> ```
> 
> It doesn't seem to cause problems, I think it's just running into some data it doesn't like at the ipld level.

Yep, no real problem, just a minor annoyance from time to time.
